# See https://docs.github.com/en/actions/guides/building-and-testing-python
# 2020-02-20 slg - For Dreamhost, we are now using Python 3.9 and Ubuntu-18.04
name: CI (pip)
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        python-version: [3.9]   # installed version on Dreamhost
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: First Test
        run: |
          echo ORG_NAME = ${{ env.ORG_NAME}}
          echo MY_NAME = ${{ env.MY_NAME}}
          echo MY_SECRET  = ${{ secret.MY_SECRET }}

      - name: Second Test
        env:
          ORG_NAME_ENV:         ${{ env.ORG_NAME }}
          MY_NAME_ENV:         ${{ env.MY_NAME }}
          MY_SECRET:           ${{ secret.MY_SECRET }}
        run: |
          echo ORG_NAME_ENV = $ORG_NAME_ENV
          echo MY_SECRET = $MY_SECRET
          echo SHA256 = `echo $MY_SECRET | openssl sha256`
